export const ROLES = {
  EMPLOYEE: "employee",
  MANAGER: "manager",
  ADMIN: "admin",
} as const;

export type ROLES = (typeof ROLES)[keyof typeof ROLES];

export const STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};

export const MESSAGES = {
  SUCCESS: {
    LOGIN: "Login successful",
    LOGOUT: "Logout successful",
    LEAVE_REQUEST_CREATED: "Leave Request Created Successfully",
    LEAVE_TYPE_CREATED: "Leave Type Created Successfully",
    LEAVES_FETCHED: "Leaves Fetched Succefully",
    LEAVE_STATUS_UPDATED: "Succesfully updated leave status",
    LEAVETYPES_FETCHED: "Successfully fetched leave types",
    CLOCK_IN: "Clocked in Successfully",
    CLOCK_OUT: "Clocked out Successfully",
    ATTENDANCE_FETCHED: "Attendance Fetched Successfully",
    PENDING_EDITS_FETCHED: "Pending Edits Fetched Successfully",
    PENDING_LEAVES_FETCHED: "Pending Leaves Fetched Successfully",
    STATUS_UPDATE_SUCCESS: "Status Updated Successfully",
    HOLIDAY_CREATE_SUCCESS: "Holiday Created Successfully",
    HOLIDAYS_FETCH_SUCCESS: "Holidays Fetched Successfully",
    HOLIDAY_UPDATE_SUCCESS: "Holiday Updated Successfully",
    HOLIDAY_DELETE_SUCCESS: "Holiday Deleted Successfully",
  },
  ERROR: {
    EMAIL_REQUIRED: "Email is Required",
    PASSWORD_REQUIRED: "Password is Required",
    INVALID_CREDENTIALS: "Invalid credentials",
    USER_NOT_FOUND: "User not found",
    PASSWORD_MISMATCH: "Password and Confirm Password do not match",
    JWT_SECRET_MISSING: "JWT secret is not configured",
    UNAUTHORIZED: "Unauthorized access",
    INVALID_TOKEN: "Invalid or expired token",
    FORBIDDEN: "Forbidden access",
    CANCEL_NOT_ALLOWED: "Cannot cancel this leave",
    LEAVES_NOT_FOUND: "No Leaves Found",
    CREATE_LEAVE_FAILED: "Failed to create leave request",
    CREATE_LEAVETYPE_FAILED: "Failed to create leave type",
    FETCH_LEAVETYPE_FAILED: "Failed to fetch leave types",
    INVALID_USER_ID: "Invalid user ID format",
    INVALID_LEAVETYPE_ID: "Invalid leave type ID format",
    INVALID_DATE_FORMAT: "Invalid date format",
    START_AFTER_END_DATE: "Start date cannot be after end date",
    PAST_DATE_SELECTION: "Cannot request leave for past dates",
    LEAVETYPE_NOT_FOUND: "Leave type not found",
    OVERLAPPING_LEAVE: "Overlapping leave request exists",
    INVALID_ID_FORMAT: "Invalid ID format",
    LEAVE_NOT_FOUND: "Leave request not found",
    UNAUTHORIZED_ACTION: "Unauthorized action",
    CANCEL_NON_PENDING: "Only pending leaves can be cancelled",
    CANCEL_STARTED_LEAVE: "Cannot cancel leave that has already started",
    INVALID_LEAVETYPE_NAME: "Leave type name must be at least 3 characters",
    INVALID_MAX_DAYS: "Maximum days must be a positive number",
    INVALID_ACCRUAL_RATE: "Accrual rate must be a positive number",
    LEAVETYPE_EXISTS: "Leave type with this name already exists",
    NO_LEAVETYPES_FOUND: "No leave types found",
    INSUFFICIENT_LEAVE_BALANCE: "Insufficient leave balance for this request",
    HALFDAY_NOT_ALLOWED:
      "Half-day requests are not allowed for this leave type",
    CLOCK_IN_UNAVAILABLE: "No clock-in found",
    ATTENDANCE_FETCH_FAILED: "Attendance Fetch Failed",
    PENDING_EDITS_FETCH_FAILED: "Pending Edits Fetch Failed",
    HOLIDAY_NOT_FOUND: "Holiday not found",
  },
};
